# Generated by Django 3.1.1 on 2020-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('duration', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
